name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  c-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Repository checkout
        uses: actions/checkout@v2
        
      - name: Install clang-format
        run: sudo apt-get install -y clang-format

      - name: Linting
        run: make lint

  build-c:
    runs-on: ubuntu-latest
    needs: c-linter
    steps:
    - uses: actions/checkout@v2
    
    - name: make
      run: make

    - name: make clean
      run: make clean

